version: '1.0.{build}'

branches:
  # whitelist
  only:
    - master
    - appveyor-update

environment:

  GEO_VERSION: '23b'

  matrix:

    # Windows python 2.7
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#      PYTHON: "C:\\Python27-x64"
#      PYTHON_ARCH: "64"
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#      PYTHON: "C:\\Python27"
#      PYTHON_ARCH: "32"

    # Windows python 3.8
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
#      PYTHON: "C:\\Python38-x64"
#      PYTHON_ARCH: "64"
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
#      PYTHON: "C:\\Python38"
#      PYTHON_ARCH: "32"

    # Windows python 3.11
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      PYTHON: "C:\\Python311-x64"
      PYTHON_ARCH: "64"
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
#      PYTHON: "C:\\Python311"
#      PYTHON_ARCH: "32"


#    # Ubuntu - python 3.11
#    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
#      PYTHON: "3.11.2"


# some sanity checks to make sure we are using the correct python
init:
  - cmd: %PYTHON%/python -V
  - cmd: %PYTHON%/python -c "import sys;print('64 Bit' if sys.maxsize  > 2**32 else '32 bit')"

#stack: python %PYTHON%

build_script:
  - ps: .\appveyor\build.ps1

test_script:
  - %PYTHON%/python setup.py test
#  - pip install -e .[dev]
#  - invoke test all


