version: '1.0.{build}'

branches:
  # whitelist
  only:
    - master
    - appveyor-update

environment:

  GEO_VERSION: '18b'

  matrix:
    # Windows w/64 bit python 3.11
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: "C:\Python311-x64"
      PYTHON_ARCH: "64"

    # Windows w/32 bit Geo & python 3.11
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: "C:\Python311"
      PYTHON_ARCH: "32"

    # Ubuntu - python 3
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "3.11.3"


#init:
#  - cmd: set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
#  - cmd: "%PYTHON%/python -V"
#  - cmd: "%PYTHON%/python -c \"import struct;print(8 * struct.calcsize(\'P\'))\""

stack: python %PYTHON%

build_script:
  - ps: .\appveyor\build.ps1

test_script:
  - python setup.py test
#  - pip install -e .[dev]
#  - invoke test all


